### ISSUE TITLE
Game crashes after removing suit

### ISSUE THREAD

**Issue by vavavr00m** [undermark5/SpillProof#1] opened 2023-03-13 18:08 UTC
A certain player's game is crashing when removing the suit, however, it might be worth noting that it works for another player who has yet to advance to Space Exploration

![image](https://user-images.githubusercontent.com/4675132/224789975-06d02b65-4871-48b7-8f9b-af1fbabe07d3.png)

**Comment by undermark5** [comment] 2023-03-13 18:13
Do you happen to have any steps to reproduce?

**Comment by undermark5** [comment] 2023-03-13 18:19
Interesting, this crash would imply that the player lost more slots than they had as bonus.

Was the mod added from the start or was it added after the fact (I don't think it should make a difference, but I also could be completely wrong)

**Comment by vavavr00m** [comment] 2023-03-13 19:59
After. Do you need anything?

**Comment by vavavr00m** [comment] 2023-03-13 20:18
Mod was added midgame. All I got from the player was they removed their suit and then it crashed.

Save game: https://mega.nz/file/7MtikRpY
Decryption key: Qc2xvU5T2-FyvRBFTjF7EnM8S_zyH139O5Nehc1k-50

Do you need anything else to fix the issue?

**Comment by undermark5** [comment] 2023-03-13 21:21
This will be good enough to allow me to start debugging the issue, if I do need anything else I'll let you know.

Because it was added mid game, I'm guessing that something in the migration is ultimately to blame. Though, it is also possible that if another mod is used that changes the armor bonuses, that could also theoretically cause this to happen (it may be possible to accommodate for such a scenario, but I'll have to do some testing)

**Comment by vavavr00m** [comment] 2023-03-13 23:35
You may also want to take a look at Schall Remains & Pickup. It was added at the same time as SpillProof. That mod should only be concerned with destroyed chests spills though.

**Comment by undermark5** [comment] 2023-04-08 21:01
Ok, I finally have been able to get around to actually debugging this. I believe the ultimate cause relates to Space Exploration, but I should be able to fix it in SpillProof. It is actually pretty much the same issue that I fixed in the 0.0.3 release, but this time, when using the Space Exploration provided respawn key (defaults to `Home`), it doesn't actually trigger the vanilla respawn event, but instead, a custom event. I should be able to conditionally add a handler for this event if Space Exploration is installed.

**Comment by undermark5** [comment] 2023-04-08 22:16
This should be solved by 92278a4

**Comment by undermark5** [comment] 2023-04-08 22:17
The best way to fix the hammerspace desync will be to trigger Space Exploration's respawn and mine the corpse to recover items. Dying naturally is also another valid approach.

**Closed as completed by undermark5** 2023-04-08 22:16 UTC
